### PR TITLE
Use CP 3.0.0

### PR DESCRIPTION
**Pull request by miguno**
Also, this PR installs JDK 8, git, and maven, so that we can build, package, and run Kafka Streams examples from https://github.com/confluentinc/examples against a secure Kafka cluster.

### CODE REVIEW

**Comment by miguno** [comment]
Please review @ijuma and @alexlod.

**Comment by miguno** [comment]
Note: I ran some instructions from http://www.confluent.io/blog/apache-kafka-security-authorization-authentication-encryption, which worked out-of-the-box against this PR (e.g. producing some data with the console producer, and read some data with the console consumer0.  So I think we can safely merge this into master.

**Comment by ijuma** [comment]
Thanks for the PR! LGTM.

**Comment by alexlod** [comment]
LGTM, too!

**Pull request merged**
